DIR_CUR = tools

TOOLS = fluentprofile2plot3d tecplotFE2plot3d \
				check_grid_plot3d check_solution_plot3d

default:	
	@echo ">>> Compiling "$(DIR_CUR)
	@for I in $(TOOLS); do make -C $$I; done
